services:
  - type: web
    name: dash-movie-dashboard
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.0"
