services:
  - type: web
    name: dash-movie-dashboard
    env: python
    plan: free
    region: singapore   # you can change this: oregon, singapore, etc.
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    autoDeploy: true
    envVars:
      PYTHON_VERSION: 3.10
